services:
  api:
    build: ./api
    ports:
      - "5000:80"
  web:
    build: ./web
    ports: 
      - "8080:80"
    environment:
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_ENVIRONMENT: "Development"
